language: objective-c
xcode_project: PromiseKit.xcodeproj
before_install:
  - brew update
  - brew install carthage
install: carthage bootstrap --verbose
xcode_scheme: [PMKiOS, PMKOSX]
xcode_sdk: [iphonesimulator8.3, macosx10.10]
osx_image: beta-xcode6.3

matrix:
  exclude:
    - xcode_scheme: PMKOSX
      xcode_sdk: iphonesimulator8.3
    - xcode_scheme: PMKiOS
      xcode_sdk: macosx10.10

branches:
  only:
    - master
